x-kong-config: &kong-env
  KONG_DATABASE: ${KONG_DATABASE:-postgres}
  KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
  KONG_PG_HOST: kong-database
  KONG_PG_USER: ${KONG_PG_USER:-kong}
  KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-mykongpassword}

services:
  ################################################
  # Database: PostgreSQL 16
  ################################################
  kong-database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-mykongpassword}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${KONG_PG_DATABASE:-kong}", "-U", "${KONG_PG_USER:-kong}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kong-net
    volumes:
      - kong_data:/var/lib/postgresql/data
    restart: unless-stopped

  ################################################
  # Migrations: Setup Database Schema
  ################################################
  kong-migrations:
    image: kong:3.9
    command: kong migrations bootstrap
    environment:
      <<: *kong-env
    networks:
      - kong-net
    depends_on:
      kong-database:
        condition: service_healthy
    restart: on-failure

  ################################################
  # Kong Gateway
  ################################################
  kong:
    image: kong:3.9
    user: "${KONG_USER:-kong}"
    environment:
      <<: *kong-env
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
      KONG_PREFIX: ${KONG_PREFIX:-/var/run/kong}
    networks:
      - kong-net
    ports:
      - "8000:8000"     # Proxy HTTP
      - "8443:8443"     # Proxy HTTPS
      - "127.0.0.1:8001:8001" # Admin API (Lokal)
      - "127.0.0.1:8002:8002" # Admin GUI (Lokal)
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 5
    read_only: true
    volumes:
      - kong_prefix_vol:${KONG_PREFIX:-/var/run/kong}
      - kong_tmp_vol:/tmp
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migrations:
        condition: service_completed_successfully
    restart: unless-stopped

  #############################################
  # Demo services
  #############################################
  alpha:
    image: timpamungkas/api-management-alpha:3.0.0
    container_name: alpha
    networks:
      kong-net:
        ipv4_address: 172.1.1.11
    depends_on:
      kong:
        condition: service_healthy

  beta:
    image: timpamungkas/api-management-beta:3.0.0
    container_name: beta
    networks:
      kong-net:
        ipv4_address: 172.1.1.12
    depends_on:
      kong:
        condition: service_healthy

  gamma:
    image: timpamungkas/api-management-gamma:3.0.0
    container_name: gamma
    networks:
      kong-net:
        ipv4_address: 172.1.1.13
    depends_on:
      kong:
        condition: service_healthy

  omega:
    image: timpamungkas/api-management-omega:3.0.0
    container_name: omega
    networks:
      kong-net:
        ipv4_address: 172.1.1.14
    depends_on:
      kong:
        condition: service_healthy

volumes:
  kong_data:
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  kong-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.1.0/24