version: '3.7'

x-kong-config:
  &kong-env
  KONG_DATABASE: ${KONG_DATABASE:-postgres}
  KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
  KONG_PG_HOST: kong-database
  KONG_PG_USER: ${KONG_PG_USER:-kong}
  KONG_PG_PASSWORD: mykongpassword

volumes:
  kong_data: {}
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  kong-net:
    external: false

services:
  ################################################
  # Kong components (Kong & PostgreSQL Database) #
  ################################################
  kong-migrations:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations bootstrap
    environment:
      <<: *kong-env
    networks:
      - kong-net
    restart: on-failure
    depends_on:
      - kong-database

  kong-migrations-up:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations up && kong migrations finish
    environment:
      <<: *kong-env
    networks:
      - kong-net
    restart: on-failure
    depends_on:
      - kong-database

  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    user: "${KONG_USER:-kong}"
    environment:
      <<: *kong-env
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "${KONG_PROXY_LISTEN:-0.0.0.0:8000}"
      KONG_ADMIN_LISTEN: "${KONG_ADMIN_LISTEN:-0.0.0.0:8001}"
      KONG_ADMIN_GUI_LISTEN: "${KONG_ADMIN_GUI_LISTEN:-0.0.0.0:8002}"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PREFIX: ${KONG_PREFIX:-/var/run/kong}
      KONG_TRACING_INSTRUMENTATIONS: "request"
    networks:
      - kong-net
    ports:
      - "${KONG_INBOUND_PROXY_LISTEN:-0.0.0.0}:8000:8000/tcp"
      - "127.0.0.1:8001:8001/tcp"
      - "127.0.0.1:8444:8444/tcp"
      - "127.0.0.1:8002:8002/tcp"
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure:5
    read_only: true
    volumes:
      - kong_prefix_vol:${KONG_PREFIX:-/var/run/kong}
      - kong_tmp_vol:/tmp
    security_opt:
      - no-new-privileges

  kong-database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-mykongpassword}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${KONG_PG_DATABASE:-kong}",
          "-U",
          "${KONG_PG_USER:-kong}"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - kong-net
    volumes:
      - kong_data:/var/lib/postgresql/data

  #############################################
  # Konga Services
  #############################################


  konga-database:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: konga_db
      POSTGRES_USER: konga
      POSTGRES_PASSWORD: mykongapassword
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "-konga",
          "-U",
          "-konga"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - kong-net

  konga-prepare:
    container_name: konga-prepare
    image: pantsel/konga
    command: "-c prepare -a postgres -u postgresql://konga:mykongapassword@konga-database:5432/konga_db"
    networks:
      - kong-net
    restart: on-failure
    depends_on:
      - konga-database
  
  konga:
    container_name: konga
    image: pantsel/konga
    restart: unless-stopped
    networks:
      - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: konga-database
      DB_USER: konga
      DB_PASSWORD: mykongapassword
      DB_DATABASE: konga_db
      # any string will OK for token
      TOKEN_SECRET: iu7YDcPLiZkozQXzZ9kka3Ee1Vid5ZgQ
      NODE_ENV: development
    depends_on:
      - konga-prepare
    ports:
      - "1337:1337"


  #############################################
  # Demo services : alpha, beta, gamma, omega #
  #############################################

  alpha:
    container_name: alpha
    image: timpamungkas/api-management-alpha:3.0.0
    restart: unless-stopped
    networks:
      - kong-net
    ports:
      - "9001:9001"
    depends_on:
      - kong
      
  beta:
    container_name: beta
    image: timpamungkas/api-management-beta:3.0.0
    restart: unless-stopped
    networks:
      - kong-net
    ports:
      - "9002:9002"
    depends_on:
      - kong
      
  gamma:
    container_name: gamma
    image: timpamungkas/api-management-gamma:3.0.0
    restart: unless-stopped
    networks:
      - kong-net
    ports:
      - "9003:9003"
    depends_on:
      - kong

  omega:
    image: timpamungkas/api-management-omega:3.0.0
    container_name: omega
    restart: unless-stopped
    networks:
      - kong-net
    ports:
      - "9004:9004"
    depends_on:
      - kong